add_to_dict(): Move to callback function
unihan-db-tpeMWywt-py3.12/lib/python3.12/site-packages/sqlalchemy/event/registry.py:291: in listen
    dispatch_collection = getattr(target.dispatch, identifier)
E   AttributeError: 'registry' object has no attribute 'dispatch'

See also: https://docs.sqlalchemy.org/en/20/orm/events.html#sqlalchemy.orm.MapperEvents.after_configured

!squash